name: flutter_getx_shopping
description: A Flutter shopping app using GetX for state management and navigation.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  dio: ^5.3.2
  cached_network_image: ^3.3.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  badges: ^3.1.1
  cloud_firestore: ^5.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true