// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjaN276ZXiMg81MoQlp33OEAXTV9brClg',
    appId: '1:809360261485:web:7e09ae1bdb488a94c61a64',
    messagingSenderId: '809360261485',
    projectId: 'flutterfiretest-b1c37',
    authDomain: 'flutterfiretest-b1c37.firebaseapp.com',
    storageBucket: 'flutterfiretest-b1c37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_tpdNNqMZEXg1iygGMjMRmdD3S88PLc',
    appId: '1:809360261485:android:dd2ca61998c473efc61a64',
    messagingSenderId: '809360261485',
    projectId: 'flutterfiretest-b1c37',
    storageBucket: 'flutterfiretest-b1c37.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjaN276ZXiMg81MoQlp33OEAXTV9brClg',
    appId: '1:809360261485:web:f8f95d3809d5723dc61a64',
    messagingSenderId: '809360261485',
    projectId: 'flutterfiretest-b1c37',
    authDomain: 'flutterfiretest-b1c37.firebaseapp.com',
    storageBucket: 'flutterfiretest-b1c37.firebasestorage.app',
  );

}